title: Axel-M-Portfolio # your name (or website title) here
logo:  # your photo (or logo) here
description: Here you can see what I made! # your text below (remove <br> elements if you don't need line breaks)
  <br><br>

  
theme: jekyll-theme-minimal
google_analytics:  # your Google Analytics tracking ID here
